-- twilio_call_recordings — replaces the earlier unresolved twilio_call_sids design
SELECT c.CUSTOMER_PHONE_DIGITS, MIN(t.EVENT_TIMESTAMP) AS occurred_at, rec.RECORDING_ID,
       'https://twilio-recordings.anyvan.com/recordings/' || rec.RECORDING_ID AS recording_url
FROM CONFORMED.PRODUCTION.CALL_TRANSCRIPT_SEGMENTS t
JOIN CONFORMED.PRODUCTION.CALL_TRANSCRIPT_CALLS rec ON rec.CALL_SID = t.CALL_SID
JOIN (SELECT DISTINCT CALL_SID, CUSTOMER_PHONE_DIGITS FROM CONFORMED.PRODUCTION.CALL_TRANSCRIPT_SEGMENTS) c ON c.CALL_SID = t.CALL_SID
WHERE RIGHT(REGEXP_REPLACE(c.CUSTOMER_PHONE_DIGITS,'[^0-9]',''), 10) = RIGHT(:phone_digits, 10)
  AND rec.RECORDING_ID LIKE 'RE%'
  AND (:date_from IS NULL OR t.EVENT_TIMESTAMP >= TO_TIMESTAMP(:date_from))
  AND (:date_to   IS NULL OR t.EVENT_TIMESTAMP <  DATEADD(day,1,TO_TIMESTAMP(:date_to)))
GROUP BY c.CUSTOMER_PHONE_DIGITS, rec.RECORDING_ID
LIMIT 500;
